name = "Delightful Automations"
author = "tweakyllama"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e97c328dc472d919046ea73eb462a00602e7ec047786451c0404407b37d7aec2"

[versions]
fabric = "0.14.23"
minecraft = "1.20.1"
