name = "Delightful Automations"
author = "tweakyllama"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2aa642d6d7ca8ac76030f0fb854700d317aa350e33f4bb425b6dffc43a88af9e"

[versions]
fabric = "0.14.23"
minecraft = "1.20.1"
