name = "Delightful Automations"
author = "tweakyllama"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "49ffc444462118db009c04bd52a47045b21d31ec51d3516e65b26933856904fc"

[versions]
fabric = "0.14.23"
minecraft = "1.20.1"
